{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "k8s-aws-operator.fullname" . }}
  labels:
    {{- include "k8s-aws-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "k8s-aws-operator.selectorLabels" . | nindent 6 }}
  endpoints:
  {{- with .Values.metrics.serviceMonitor.endpoints }}
  {{ . | toYaml | nindent 2 }}
  {{- end}}
{{- end }}
