{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-aws-operator.fullname" . }}-metrics
  labels:
    {{- include "k8s-aws-operator.labels" . | nindent 4 }}
spec:
  {{- with .Values.metrics.service.clusterIP }}
  clusterIP: {{ . | quote }}
  {{- end }}
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    {{- include "k8s-aws-operator.selectorLabels" . | nindent 4 }}
{{- end }}
